# Generated by Django 5.1.1 on 2024-09-20 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bike',
            name='basket',
        ),
    ]
