# Generated by Django 5.1.1 on 2024-09-20 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_bike_basket'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bike',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shop.bike'),
        ),
    ]
